version: '3.8'
services:
  api:
    container_name: nestjs-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PORT=8888
      - BASE_URL=/api/v1
      - DATABASE_URL=postgresql://postgres:0000@postgres:5432/doctors-office-api-itexc-group?schema=public
      - JWT_SECRET=SA0IxWPHuqGPQhuY6uHfV7gRStT2XtGYmoXRNazuW8Y
    networks:
      - app-network
    command: sh -c "npx prisma migrate deploy && npm run start:prod"
    
  postgres:
    container_name: postgres-db
    image: postgres:17
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
      - POSTGRES_DB=doctors-office-api-itexc-group
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d doctors-office-api-itexc-group"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge